runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /2048
  static_dir: www/2048

- url: /spaceGame
  static_dir: www/spaceGame

